### PR TITLE
Fix facts in justification, add early arithmetics evaluation

### LINKED ISSUE #159: Program unsatisfiable because arithmetic terms are not evaluated
A program that is actually satisfiable is reported to be unsatisfiable, apparently because arithmetic terms are not evaluated in time.

Can be reproduced with the KnightTourWithHoles problem.

Encoding: `encoding.asp` from [ASP Competition 2015](http://aspcomp2015.dibris.unige.it/KnightTourWithHoles.zip)

Instance: Example from [ASP Competition 2013](https://www.mat.unical.it/aspcomp2013/KnightTour):
```
size(9).
forbidden(1,9). forbidden(2,9). forbidden(3,9). forbidden(4,9). forbidden(5,9). forbidden(6,9). forbidden(7,9). forbidden(8,9). forbidden(9,9).
forbidden(9,1). forbidden(9,2). forbidden(9,3). forbidden(9,4). forbidden(9,5). forbidden(9,6). forbidden(9,7). forbidden(9,8). forbidden(9,9).
```

### PR DESCRIPTION
**Pull request by AntoniusW**
Fixes #159.

### CODE REVIEW

File: src/test/java/at/ac/tuwien/kr/alpha/common/terms/TestMinusTerm.java [hunk 1]
```diff
@@ -41,14 +41,14 @@
 
 	@Test
 	public void testNormalizeVariablesNoVariable() {
-		MinusTerm m2 = MinusTerm.getInstance(ConstantTerm.getInstance(2));
+		Term m2 = MinusTerm.getInstance(ConstantTerm.getInstance(2));
```
Comment (rtaupe) [inline src/test/java/at/ac/tuwien/kr/alpha/common/terms/TestMinusTerm.java]: I do not understand the rationale behind the changes in this file.

Comment (AntoniusW) [reply src/test/java/at/ac/tuwien/kr/alpha/common/terms/TestMinusTerm.java]: Rationale: if an ArithmeticTerm or MinusTerm is ground `getInstance` now returns the corresponding ConstantTerm, hence `MinusTerm.getInstance(..)` now only returns `Term` instead of `MinusTerm`. In the case here it returns a `ConstantTerm`.
